### ISSUE TITLE
Description in readme is better than github description

### ISSUE THREAD

**Issue by sheldon** [oh-my-fish/plugin-brew#3]
We use github description for the omf describe command. Any chance you could update the github description to match the readme?

'Oh My Fish plugin to integrate Homebrew paths into shell.'

**Comment by bpinto** [comment]
I can't do this over mobile (I'm on vacations), but will do when I get back if nobody does it before.

**Comment by bpinto** [comment]
Guess what? I can use the desktop version on mobile (had forgotten about it)

Thanks!
